export interface CustomStyles {
  bgColor: string;
  textColor: string;
  borderColor: string;
  iconSize: number;
  sidebarWidth: number;
  borderRadius: number;
  fontFamily: string;
  fontSize: number;
  hoverBackgroundColor: string;
  activeBackgroundColor: string;
  activeTextColor: string;
  iconColor: string;
  uiBackgroundColor: string;
  backgroundImage: string;
  backgroundVideo: string;
}

export const defaultStyles: CustomStyles = {
  bgColor: '#1f2937',
  textColor: '#f3f4f6',
  borderColor: '#374151',
  iconSize: 20,
  sidebarWidth: 128,
  borderRadius: 8,
  fontFamily: 'SF Pro Display, sans-serif',
  fontSize: 14,
  hoverBackgroundColor: '#374151',
  activeBackgroundColor: '#4b5563',
  activeTextColor: '#ffffff',
  iconColor: '#9ca3af',
  uiBackgroundColor: '#111827',
  backgroundImage: '',
  backgroundVideo: '',
};

export const presetThemes = {
  dark: { ...defaultStyles },
  light: {
    ...defaultStyles,
    bgColor: '#ffffff',
    textColor: '#333333',
    borderColor: '#e5e7eb',
    hoverBackgroundColor: '#f3f4f6',
    activeBackgroundColor: '#e5e7eb',
    activeTextColor: '#000000',
    iconColor: '#4b5563',
    uiBackgroundColor: '#f0f2f5',
    fontFamily: 'Inter, sans-serif',
  },
  blue: {
    ...defaultStyles,
    bgColor: '#e0f2fe',
    textColor: '#0c4a6e',
    borderColor: '#7dd3fc',
    hoverBackgroundColor: '#bae6fd',
    activeBackgroundColor: '#7dd3fc',
    activeTextColor: '#0c4a6e',
    iconColor: '#0369a1',
    uiBackgroundColor: '#f0f9ff',
    fontFamily: 'Roboto, sans-serif',
  },
  green: {
    ...defaultStyles,
    bgColor: '#dcfce7',
    textColor: '#166534',
    borderColor: '#86efac',
    hoverBackgroundColor: '#bbf7d0',
    activeBackgroundColor: '#86efac',
    activeTextColor: '#166534',
    iconColor: '#16a34a',
    uiBackgroundColor: '#f0fdf4',
    fontFamily: 'Outfit, sans-serif',
  },
  purple: {
    ...defaultStyles,
    bgColor: '#f3e8ff',
    textColor: '#581c87',
    borderColor: '#d8b4fe',
    hoverBackgroundColor: '#e9d5ff',
    activeBackgroundColor: '#d8b4fe',
    activeTextColor: '#581c87',
    iconColor: '#9333ea',
    uiBackgroundColor: '#faf5ff',
    fontFamily: 'Poppins, sans-serif',
  },
  amber: {
    ...defaultStyles,
    bgColor: '#fef3c7',
    textColor: '#92400e',
    borderColor: '#fcd34d',
    hoverBackgroundColor: '#fde68a',
    activeBackgroundColor: '#fcd34d',
    activeTextColor: '#92400e',
    iconColor: '#d97706',
    uiBackgroundColor: '#fffbeb',
    fontFamily: 'DM Sans, sans-serif',
  },
  rose: {
    ...defaultStyles,
    bgColor: '#ffe4e6',
    textColor: '#9f1239',
    borderColor: '#fda4af',
    hoverBackgroundColor: '#fecdd3',
    activeBackgroundColor: '#fda4af',
    activeTextColor: '#9f1239',
    iconColor: '#e11d48',
    uiBackgroundColor: '#fff1f2',
    fontFamily: 'Plus Jakarta Sans, sans-serif',
  },
  slate: {
    ...defaultStyles,
    bgColor: '#f8fafc',
    textColor: '#334155',
    borderColor: '#cbd5e1',
    hoverBackgroundColor: '#f1f5f9',
    activeBackgroundColor: '#e2e8f0',
    activeTextColor: '#0f172a',
    iconColor: '#64748b',
    uiBackgroundColor: '#ffffff',
    fontFamily: 'Source Sans Pro, sans-serif',
  },
  midnight: {
    ...defaultStyles,
    bgColor: '#020617',
    textColor: '#e2e8f0',
    borderColor: '#1e293b',
    hoverBackgroundColor: '#0f172a',
    activeBackgroundColor: '#1e293b',
    activeTextColor: '#f8fafc',
    iconColor: '#94a3b8',
    uiBackgroundColor: '#000000',
    fontFamily: 'Space Grotesk, sans-serif',
  },
  forest: {
    ...defaultStyles,
    bgColor: '#064e3b',
    textColor: '#d1fae5',
    borderColor: '#065f46',
    hoverBackgroundColor: '#065f46',
    activeBackgroundColor: '#047857',
    activeTextColor: '#ecfdf5',
    iconColor: '#6ee7b7',
    uiBackgroundColor: '#064e3b',
    fontFamily: 'Montserrat, sans-serif',
  },
  sunset: {
    ...defaultStyles,
    bgColor: '#7c2d12',
    textColor: '#ffedd5',
    borderColor: '#9a3412',
    hoverBackgroundColor: '#9a3412',
    activeBackgroundColor: '#c2410c',
    activeTextColor: '#fff7ed',
    iconColor: '#fdba74',
    uiBackgroundColor: '#7c2d12',
    fontFamily: 'Urbanist, sans-serif',
  },
  ocean: {
    ...defaultStyles,
    bgColor: '#0c4a6e',
    textColor: '#e0f2fe',
    borderColor: '#0369a1',
    hoverBackgroundColor: '#0369a1',
    activeBackgroundColor: '#0284c7',
    activeTextColor: '#f0f9ff',
    iconColor: '#7dd3fc',
    uiBackgroundColor: '#0c4a6e',
    fontFamily: 'Albert Sans, sans-serif',
  },
  highContrast: {
    ...defaultStyles,
    bgColor: '#000000',
    textColor: '#ffffff',
    borderColor: '#ffffff',
    hoverBackgroundColor: '#1a1a1a',
    activeBackgroundColor: '#333333',
    activeTextColor: '#ffffff',
    iconColor: '#ffffff',
    uiBackgroundColor: '#000000',
    fontFamily: 'Arial, sans-serif',
    fontSize: 16,
  },
  mint: {
    ...defaultStyles,
    bgColor: '#ecfdf5',
    textColor: '#065f46',
    borderColor: '#6ee7b7',
    hoverBackgroundColor: '#d1fae5',
    activeBackgroundColor: '#6ee7b7',
    activeTextColor: '#065f46',
    iconColor: '#059669',
    uiBackgroundColor: '#f0fdf9',
    fontFamily: 'Red Hat Display, sans-serif',
  },
  coffee: {
    ...defaultStyles,
    bgColor: '#44403c',
    textColor: '#fef3c7',
    borderColor: '#57534e',
    hoverBackgroundColor: '#57534e',
    activeBackgroundColor: '#78716c',
    activeTextColor: '#fffbeb',
    iconColor: '#d6d3d1',
    uiBackgroundColor: '#292524',
    fontFamily: 'Bitter, serif',
  },
  nordic: {
    ...defaultStyles,
    bgColor: '#f8fafc',
    textColor: '#1e293b',
    borderColor: '#cbd5e1',
    hoverBackgroundColor: '#f1f5f9',
    activeBackgroundColor: '#e2e8f0',
    activeTextColor: '#0f172a',
    iconColor: '#64748b',
    uiBackgroundColor: '#ffffff',
    fontFamily: 'Commissioner, sans-serif',
  },
  cyberpunk: {
    ...defaultStyles,
    bgColor: '#18181b',
    textColor: '#fef08a',
    borderColor: '#3f3f46',
    hoverBackgroundColor: '#27272a',
    activeBackgroundColor: '#52525b',
    activeTextColor: '#fef08a',
    iconColor: '#d4d4d8',
    uiBackgroundColor: '#09090b',
    fontFamily: 'Orbitron, sans-serif',
  },
  pastel: {
    ...defaultStyles,
    bgColor: '#fdf2f8',
    textColor: '#831843',
    borderColor: '#fbcfe8',
    hoverBackgroundColor: '#fce7f3',
    activeBackgroundColor: '#fbcfe8',
    activeTextColor: '#831843',
    iconColor: '#db2777',
    uiBackgroundColor: '#fff1f2',
    fontFamily: 'Quicksand, sans-serif',
  },
};
