name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: 'Features:'
    labels:
      - 'UI'
      - 'enhancement'

  - title: 'Bug Fixes:'
    labels:
      - 'bug'

  - title: 'Documentation:'
    labels:
      - 'documentation'

  - title: 'Others:'
    labels: []

change-template: '- $TITLE (#$NUMBER) by @$AUTHOR'

template: |
  # What's Changed

  $CHANGES

  ## Special thanks to all our contributors:

  $CONTRIBUTORS