repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.10
    hooks:
      - id: ruff
        args: [--fix]

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3

  - repo: local
    hooks:
      - id: mypy-backend
        name: mypy (backend)
        entry: mypy --config-file backend/pyproject.toml
        language: system
        files: ^backend/.*\.py$
        require_serial: true

      - id: mypy-sync-microservice
        name: mypy (sync microservice)
        entry: mypy --config-file sync-microservice/pyproject.toml
        language: system
        files: ^sync-microservice/.*\.py$
        require_serial: true
