services:
 web:
   develop:
     watch:
       - path: ./DockerFile
         action: rebuild
       - path: ./requirements.txt
         action: rebuild
       - path: .
         target: /app
         action: sync
   volumes:
     - type: bind
       source: ./
       target: /root/app
     - type: bind
       source: '~'
       target: /root
   build:
     context: .
     dockerfile: DockerFile
   ports:
     - 5000:5000
   