FROM python:3-slim

# Define the volume and workdir using absolute paths
VOLUME /root
WORKDIR /root/app

# Copy the current directory contents into the container at /root/host/app
COPY . .

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Make port 5000 available to the world outside this container
EXPOSE 5000

# Run main.py when the container launches
CMD ["python", "main.py"]

