site_name: PictoPy
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      primary: red
      accent: red
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list

extra_css:
  - stylesheets/output.css
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Overview:
      - Introduction: overview/introduction.md
      - Features: overview/features.md
      - Architecture: overview/architecture.md
  - Backend:
      - Setup: backend/setup.md
      - Directory Structure: backend/directory-structure.md
      - Database: backend/database.md
      - API: backend/api.md
      - Image Processing: backend/image-processing.md
  - Frontend:
      - Setup: frontend/setup.md
      - UI Components: frontend/ui-components.md
      - State Management: frontend/state-management.md
      - Gallery View: frontend/gallery-view.md
