import asyncio
import hmac
import os
import platform
import signal
from fastapi import APIRouter, Header, HTTPException
from pydantic import BaseModel
from app.config.settings import SHUTDOWN_TOKEN
from app.utils.watcher import watcher_util_stop_folder_watcher
from app.logging.setup_logging import get_sync_logger

logger = get_sync_logger(__name__)

router = APIRouter(tags=["Shutdown"])


class ShutdownResponse(BaseModel):
    """Response model for shutdown endpoint."""

    status: str
    message: str


async def _delayed_shutdown(delay: float = 0.1):
    """
    Shutdown the server after a short delay to allow the response to be sent.

    Args:
        delay: Seconds to wait before signaling shutdown (kept minimal)
    """
    await asyncio.sleep(delay)
    logger.info("Exiting sync microservice...")

    if platform.system() == "Windows":
        # Windows: SIGTERM doesn't work reliably with uvicorn subprocesses
        os._exit(0)
    else:
        # Unix (Linux/macOS): SIGTERM allows cleanup handlers to run
        os.kill(os.getpid(), signal.SIGTERM)


@router.post("/shutdown", response_model=ShutdownResponse)
async def shutdown(x_shutdown_token: str = Header(...)):
    """
    Gracefully shutdown the sync microservice.

    This endpoint requires the ``X-Shutdown-Token`` header to match the token
    generated by the backend at startup.  The token is shared between services
    via a temporary file, so only the PictoPy application itself can trigger
    shutdown — arbitrary local processes are rejected with 403 Forbidden.

    This endpoint:
    1. Validates the shutdown token
    2. Stops the folder watcher
    3. Schedules server termination after response is sent
    4. Returns confirmation to the caller

    Returns:
        ShutdownResponse with status and message
    """
    # Use constant-time comparison to prevent timing-based token guessing
    if not hmac.compare_digest(x_shutdown_token, SHUTDOWN_TOKEN):
        logger.warning("Shutdown attempt rejected: invalid token")
        raise HTTPException(status_code=403, detail="Forbidden")

    logger.info("Shutdown request received for sync microservice")

    try:
        # Stop the folder watcher first
        watcher_util_stop_folder_watcher()
    except Exception as e:
        logger.error(f"Error stopping folder watcher: {e}")

    # Define callback to handle potential exceptions in the background task
    def _handle_shutdown_exception(task: asyncio.Task):
        try:
            task.result()
        except Exception as e:
            logger.error(f"Sync shutdown task failed: {e}")

    # Schedule shutdown after response is sent
    shutdown_task = asyncio.create_task(_delayed_shutdown())
    shutdown_task.add_done_callback(_handle_shutdown_exception)

    return ShutdownResponse(
        status="shutting_down",
        message="Sync microservice shutdown initiated. Watcher stopped.",
    )
