name: "✨ Feature Request"
description: "Suggest an idea for this project "
title: "Feat:"
labels: [Feat, Needs Triage]
body:
  - type: textarea
    attributes:
      label: "Describe the feature"
      description: "Please describe the feature you would like to see"
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Add ScreenShots"
      description: "Add sufficient SS to explain your issue."
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: "Record"
      options:
        - label: "I agree to follow this project's Code of Conduct"
          required: true
        - label: "I want to work on this issue"
  - type: checkboxes
    attributes:
      label: "Checklist before Submitting."
      options:
        - label: "Have you updated docs for it?."
          required: true
        - label: "Have you added unit tests?."
          required: false
        - label: "Have you made sure unit tests pass?"
          required: false
        - label: "Have you made sure code formatting is correct?"
          required: true
        - label: "Does it contain any style related issues?"
          required: false
          
