export const ROUTES = {
  AI: 'ai-tagging',
  FAVOURITES: 'favourites',
  HOME: 'home',
  DASHBOARD: 'dashboard',
  PHOTOS: 'photos',
  VIDEOS: 'videos',
  SETTINGS: 'settings',
  ALBUMS: 'albums',
  MEMORIES: 'memories',
  MEMORIES_SETTINGS: 'memories/settings',
  PERSON: 'person/:clusterId',
  MODEL_MANAGER: 'model-manager',
  SEARCH: 'search',
};
