name: Sync Issue Labels to PR

on:
  pull_request:
    types: [opened, reopened, synchronize, edited]

jobs:
  sync-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Extract linked issues from PR body
        id: issues
        run: |
          BODY="${{ github.event.pull_request.body }}"
          # Grab all #123 style references
          ISSUES=$(echo "$BODY" | grep -oE '#[0-9]+' | tr -d '#' | tr '\n' ' ')
          echo "issues=$ISSUES" >> $GITHUB_OUTPUT

      - name: Collect labels from linked issues
        if: steps.issues.outputs.issues != ''
        id: labels
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ALL_LABELS=""

          for ISSUE_NUM in ${{ steps.issues.outputs.issues }}; do
            echo "Checking #$ISSUE_NUM"
            IS_PR=$(gh api repos/${{ github.repository }}/issues/$ISSUE_NUM --jq '.pull_request // empty' || echo "")

            if [ -n "$IS_PR" ]; then
              echo "#$ISSUE_NUM is a PR, skipping"
              continue
            fi

            LABELS=$(gh issue view $ISSUE_NUM --json labels -q '.labels[].name')
            if [ -n "$LABELS" ]; then
              echo "Found labels on issue #$ISSUE_NUM: $LABELS"
              ALL_LABELS="$ALL_LABELS"$'\n'"$LABELS"
            fi
          done

          # Deduplicate, remove blanks, and join with commas
          ALL_LABELS=$(echo "$ALL_LABELS" | sed '/^$/d' | sort -u | paste -sd, -)

          if [ -n "$ALL_LABELS" ]; then
            echo "labels=$ALL_LABELS" >> $GITHUB_OUTPUT
          fi

      - name: Apply labels to PR
        if: steps.labels.outputs.labels != ''
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Applying labels: ${{ steps.labels.outputs.labels }}"
          gh pr edit ${{ github.event.pull_request.number }} --add-label "${{ steps.labels.outputs.labels }}"

      - name: Comment if no linked issues
        if: steps.issues.outputs.issues == ''
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr comment ${{ github.event.pull_request.number }} \
            --body "⚠️ This pull request does not reference any issues. Please link an issue (e.g., 'Fixes #issue_number') so labels can be synced."
