name: Merge Check

on:
  pull_request_review:
    types: [submitted]

jobs:
  build-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: true
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            curl \
            build-essential \
            libgtk-3-dev \
            libwebkit2gtk-4.0-dev \
            libwebkit2gtk-4.1-dev \
            libappindicator3-dev \
            wget \
            xz-utils \
            libssl-dev \
            libglib2.0-dev \
            libgirepository1.0-dev \
            pkg-config \
            software-properties-common \
            libjavascriptcoregtk-4.0-dev \
            libjavascriptcoregtk-4.1-dev \
            libsoup-3.0-dev \
            librsvg2-dev \
            file

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        
      - name: Install Tauri CLI
        run: cargo install tauri-cli

      - name: Navigate to frontend directory
        run: cd frontend

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'
          
      - name: Install frontend dependencies
        run: npm install
        
      - name: Build Tauri
        run: npm run tauri build